version: "3.9"
services:
  db_mir_exchange:
    image: mongo:4.4.6
    container_name: db_mir_exchange
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /var/lib/docker/containers/mc1/db/data:/data/db
    ports:
      - "27017:27017"
    restart: always

  mir_exchange:
    image: qmbo/mir_exchange:0.0.1
    container_name: mir_exchange
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: telegram_messages_sender_broker:49150
      SPRING_DATA_MONGODB_URI: mongodb://root:password@db_mir_exchange/mirexchange?authSource=admin
    ports:
      - "49007:49007"
    depends_on:
      - db_mir_exchange
    restart: always

#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: password
#      ME_CONFIG_MONGODB_URL: mongodb://root:password@db_mir_exchange:27017/

networks:
  default:
    external:
      name: telegram_messages_sender_net
